#!/usr/bin/env bash
# =============================================================
# MultiModal Voice AI — Local Environment Setup
# =============================================================
# Run this once after cloning on a new machine:
#   chmod +x setup.sh && ./setup.sh
#
# Requires the GitHub CLI (gh) to be installed and authenticated:
#   brew install gh && gh auth login
# =============================================================

set -euo pipefail

REPO="garrylindsay/MultiModalVoiceAI"
ROOT_ENV=".env"
SERVER_ENV="react-app/server/.env"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║   MultiModal Voice AI — Environment Setup ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════╝${NC}"
echo ""

# --- Check gh CLI ---
if ! command -v gh &>/dev/null; then
  echo -e "${RED}ERROR: GitHub CLI (gh) is not installed.${NC}"
  echo "  Install it with:  brew install gh"
  echo "  Then run:         gh auth login"
  exit 1
fi

if ! gh auth status &>/dev/null; then
  echo -e "${RED}ERROR: Not logged in to GitHub CLI.${NC}"
  echo "  Run:  gh auth login"
  exit 1
fi

echo -e "${GREEN}✓ GitHub CLI authenticated${NC}"
echo ""

# --- Helper: fetch a GitHub Variable value ---
get_var() {
  gh api "repos/${REPO}/actions/variables/$1" --jq '.value' 2>/dev/null || echo ""
}

# --- Fetch non-sensitive variables from GitHub ---
echo -e "${CYAN}Fetching config from GitHub Variables...${NC}"
LLM_PROVIDER=$(get_var LLM_PROVIDER)
LMSTUDIO_BASE_URL=$(get_var LMSTUDIO_BASE_URL)
LMSTUDIO_MODEL=$(get_var LMSTUDIO_MODEL)
GOOGLE_MODEL=$(get_var GOOGLE_MODEL)
TTS_PROVIDER=$(get_var TTS_PROVIDER)
OPENAI_TTS_MODEL=$(get_var OPENAI_TTS_MODEL)
OPENAI_TTS_VOICE=$(get_var OPENAI_TTS_VOICE)
OPENAI_STT_MODEL=$(get_var OPENAI_STT_MODEL)
PORT=$(get_var PORT)
NODE_ENV=$(get_var NODE_ENV)

# Apply defaults if variables couldn't be fetched
LLM_PROVIDER=${LLM_PROVIDER:-lmstudio}
LMSTUDIO_BASE_URL=${LMSTUDIO_BASE_URL:-http://localhost:1234/v1}
LMSTUDIO_MODEL=${LMSTUDIO_MODEL:-qwen3.5-9b}
GOOGLE_MODEL=${GOOGLE_MODEL:-gemini-3.1-flash-lite-preview}
TTS_PROVIDER=${TTS_PROVIDER:-browser}
OPENAI_TTS_MODEL=${OPENAI_TTS_MODEL:-tts-1}
OPENAI_TTS_VOICE=${OPENAI_TTS_VOICE:-fable}
OPENAI_STT_MODEL=${OPENAI_STT_MODEL:-whisper-1}
PORT=${PORT:-3001}
NODE_ENV=${NODE_ENV:-development}

echo -e "${GREEN}✓ Config loaded${NC}"
echo ""

# --- Prompt for secrets (API keys) ---
echo -e "${YELLOW}Enter your API keys (input is hidden):${NC}"
echo ""

read -rsp "  OpenAI API Key  (sk-...): " OPENAI_API_KEY
echo ""
read -rsp "  Google API Key  (AIza...): " GOOGLE_API_KEY
echo ""
echo ""

if [[ -z "$OPENAI_API_KEY" || -z "$GOOGLE_API_KEY" ]]; then
  echo -e "${RED}ERROR: Both API keys are required.${NC}"
  exit 1
fi

# --- Write root .env ---
echo -e "${CYAN}Writing ${ROOT_ENV}...${NC}"
cat > "$ROOT_ENV" << EOF
# OpenAI API Key
OPENAI_API_KEY="${OPENAI_API_KEY}"

# Google API Key
GOOGLE_API_KEY="${GOOGLE_API_KEY}"
EOF

# --- Write react-app/server/.env ---
echo -e "${CYAN}Writing ${SERVER_ENV}...${NC}"
mkdir -p "$(dirname "$SERVER_ENV")"
cat > "$SERVER_ENV" << EOF
# ===========================================
# SECURE API CONFIGURATION
# ===========================================
# Generated by setup.sh — DO NOT commit this file
# ===========================================

# --- LLM Providers ---
LLM_PROVIDER=${LLM_PROVIDER}
LMSTUDIO_BASE_URL=${LMSTUDIO_BASE_URL}
LMSTUDIO_MODEL=${LMSTUDIO_MODEL}

# Google Gemini
GOOGLE_API_KEY=${GOOGLE_API_KEY}
GOOGLE_MODEL=${GOOGLE_MODEL}

# --- TTS Providers ---
TTS_PROVIDER=${TTS_PROVIDER}

# OpenAI (TTS + STT)
OPENAI_API_KEY=${OPENAI_API_KEY}
OPENAI_TTS_MODEL=${OPENAI_TTS_MODEL}
OPENAI_TTS_VOICE=${OPENAI_TTS_VOICE}
OPENAI_STT_MODEL=${OPENAI_STT_MODEL}

# Server
PORT=${PORT}
NODE_ENV=${NODE_ENV}
EOF

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║           Setup complete! ✓               ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════╝${NC}"
echo ""
echo "  Created: ${ROOT_ENV}"
echo "  Created: ${SERVER_ENV}"
echo ""
echo -e "  Start the app:  ${CYAN}cd react-app && npm run dev${NC}"
echo ""
